# REST Client tests

@baseUrl = http://localhost:3333

### dev add
POST {{baseUrl}}/devs HTTP/1.1
Content-Type: application/json

{
    "github_username": "georgejr3211",
    "techs": "ReactJS, React Native, NodeJS",
    "latitude": -19.7572881,
    "longitude": -47.9545283
}


### devs list
GET {{baseUrl}}/devs
Content-Type: application/json


### search devs
GET {{baseUrl}}/search?latitude=-47.9515105&longitude=-19.7604797&techs=ReactJS,VueJS
Content-Type: application/json